
export const content = {
  pl: {
    meta: {
      title: "AIO AUTOMATE™ – Automatyzacja marketingu od briefu do publikacji (PL)",
      description: "Platforma AI do tworzenia i publikacji kampanii z warstwą legal-tech: C2PA/SynthID, transfer praw, zgodność RODO. Od briefu do wyników.",
    },
    header: {
      nav: {
        features: "Funkcje",
        pricing: "Cennik",
        faq: "FAQ",
      },
      cta: "Rozpocznij pilotaż",
      login: "Zaloguj się",
      register: "Zarejestruj się",
      logout: "Wyloguj",
    },
    hero: {
      title: "Automatyzacja marketingu",
      subtitle: "od briefu do publikacji.",
      description: "Nasze autonomiczne agenty AI przejmują cały proces kampanii, a wbudowana warstwa legal-tech zapewnia pełne bezpieczeństwo prawne i transparentność.",
      badge: "C2PA/SynthID w standardzie",
      cta: "Dołącz do listy zainteresowanych"
    },
    problem: {
      pretitle: "Problem",
      title: "Marketing w erze AI to obietnica i chaos.",
      description: "Zespoły marketingowe toną w dziesiątkach narzędzi, a presja na szybkość, koszty i jakość rośnie. Generatywne AI obiecuje rewolucję, ale wprowadza chaos prawny i ryzyko utraty kontroli nad marką.",
      cards: [
        { title: "Rozproszony stack", description: "Żonglowanie subskrypcjami, brak integracji i spójności danych. Czas ucieka na manualnej pracy, a nie na strategii." },
        { title: "Presja i kompromisy", description: "Niekończąca się walka między szybkością, jakością a budżetem. Kreatywność ustępuje miejsca gaszeniu pożarów." },
        { title: "Chaos prawny AI", description: "Kto jest właścicielem treści? Czy można jej użyć komercyjnie? Brak transparentności i standardów to realne ryzyko biznesowe." },
      ]
    },
    solution: {
      pretitle: "Rozwiązanie",
      title: "Jedna platforma. Pełna kontrola. Bezpieczeństwo.",
      description: "AIO AUTOMATE™ to zintegrowany system operacyjny dla marketingu. Automatyzujemy cały cykl życia kampanii – od generacji treści, przez precyzyjną postprodukcję, aż po publikację, analizę i optymalizację.",
      points: [
        { title: "End-to-End Workflow:", description: "Generuj foto, wideo, 3D i copy w jednym miejscu." },
        { title: "Fine Control & Post/VFX:", description: "Pełna kontrola nad głosem, muzyką, kadrem i kolorem." },
        { title: "Wbudowana warstwa prawna:", description: "Standard C2PA/SynthID, transfer praw i zgodność z regulacjami." },
      ]
    },
    howItWorks: {
        title: "Jak to działa? Sześć prostych kroków.",
        description: "Od pomysłu do globalnej kampanii w czasie, który do tej pory zajmowało napisanie jednego maila.",
        steps: [
            { name: '1. Brand Book', description: 'Wprowadź logo, kolory, fonty i ton głosu. Nasze AI uczy się Twojej marki, by zapewnić 100% spójności.' },
            { name: '2. Precyzyjny brief', description: 'Określ cel, ofertę, target i CTA. Prześlij pliki PDF z dodatkowymi informacjami. Nasz Brief Intelligence Engine zrozumie kontekst.' },
            { name: '3. Propozycje kampanii', description: 'W ciągu minut otrzymasz 2-3 warianty koncepcji kreatywnych, w pełni zgodnych z briefem i Twoim Brand Kitem.' },
            { name: '4. Generacja & Fine Control', description: 'Po akceptacji koncepcji, platforma generuje wszystkie potrzebne assety. Użyj panelu Fine Control do finalnych poprawek.' },
            { name: '5. Publikacja', description: 'Zintegruj konta Meta, TikTok i inne. Zaplanuj publikacje, a nasz Media Automator zajmie się resztą.' },
            { name: '6. Analiza i optymalizacja', description: 'Śledź wyniki w czasie rzeczywistym. AI Performance Engine analizuje dane i proponuje automatyczne korekty dla przyszłych kampanii.' },
        ]
    },
    features: {
      title: "Stworzony dla efektywności i kontroli.",
      description: "Każda funkcja AIO AUTOMATE™ została zaprojektowana, by eliminować manualną pracę, zwiększać kreatywność i zapewniać pełne bezpieczeństwo.",
      featureList: [
        { name: 'Brief Intelligence Engine', description: 'Analizuje briefy, dokumenty i URL-e, by w pełni zrozumieć kontekst kampanii.' },
        { name: 'Brand Kit Lock + Policy Engine', description: 'Gwarantuje 100% zgodności z identyfikacją wizualną i polityką marki (guardrails).' },
        { name: 'Creative Factory', description: 'Generuje tysiące wariantów kreacji (Mass) lub pojedyncze, dopracowane assety (High-End).' },
        { name: 'Feedback Loop Engine', description: 'Uczy się Twojego gustu i preferencji na podstawie ocen i edycji, by kolejne propozycje były jeszcze lepsze.' },
        { name: 'Media Automator', description: 'Planuje i publikuje treści na platformach społecznościowych, oszczędzając Twój czas.' },
        { name: 'AI Performance Engine', description: 'Analizuje wyniki kampanii i dostarcza rekomendacji optymalizacyjnych.' },
        { name: 'Legal & Rights Vault', description: 'Przechowuje certyfikaty C2PA/SynthID i dokumenty transferu praw autorskich dla każdego assetu.' },
        { name: 'Fine Control Panel', description: 'Intuicyjne narzędzia postprodukcyjne do precyzyjnej kontroli nad każdym detalem kreacji.' },
      ]
    },
    integrations: {
        title: "Zintegrowany z narzędziami, których już używasz",
        description: "AIO AUTOMATE™ łączy się z Twoim stosem technologicznym, tworząc płynny przepływ pracy bez potrzeby przełączania kontekstu. Mniej klikania, więcej tworzenia.",
        logos: ['Meta', 'TikTok', 'Google', 'Salesforce', 'Adobe', 'HubSpot', 'Slack', 'Zapier']
    },
    legalSafety: {
      pretitle: "Legal & Safety First",
      title: "Twórz bez obaw. Publikuj z pewnością.",
      description: "W erze dezinformacji i chaosu prawnego, AIO AUTOMATE™ stawia na transparentność. Jesteśmy pierwszą platformą, która integruje standardy C2PA i SynthID na każdym etapie, dając Ci niepodważalny dowód pochodzenia i własności treści.",
      points: [
        "Certyfikaty C2PA/SynthID dla każdego assetu",
        "Automatyczny transfer praw do użytku komercyjnego",
        "Zgodność z RODO i UE AI Act",
        "Transparentność modeli AI użytych do generacji",
      ],
      highlight: "Każdy asset otrzymuje C2PA/SynthID. Masz jasność praw komercyjnych.",
    },
    icp: {
      title: "Zbudowane dla liderów. Skalowalne dla każdego.",
      description: "Niezależnie od wielkości Twojego zespołu, AIO AUTOMATE™ dostosowuje się do Twoich potrzeb, stając się potężnym narzędziem w rękach strategów.",
      profiles: [
        { name: 'Agencje Marketingowe', description: 'Od pitchu do publikacji, samodzielnie i szybciej. Zaskocz klienta tempem i jakością, jednocześnie redukując koszty operacyjne. Skaluj obsługę bez powiększenia zespołu.', cta: 'Dołącz do listy' },
        { name: 'Marki D2C / eCommerce', description: 'Twórz nieograniczoną liczbę wariantów performance contentu. Wbudowana pętla optymalizacji i analiza ROI pozwolą Ci maksymalizować konwersję i wyprzedzić konkurencję.', cta: 'Dołącz do listy' },
        { name: 'Małe Firmy i Twórcy', description: 'Twoje osobiste centrum marketingowe. Zarządzaj całym marketingiem samodzielnie, bez potrzeby zatrudniania agencji czy freelancerów. Od strategii po codzienne posty.', cta: 'Dołącz do listy' },
      ]
    },
    pricing: {
      title: "Prosty cennik. Potężne możliwości.",
      description: "Wybierz plan, który rośnie razem z Tobą. Zacznij dziś i skaluj bez ograniczeń.",
      monthly: "Miesięcznie",
      yearly: "Rocznie",
      yearly_save: "(-15%)",
      popular: "Najpopularniejszy",
      plans: [
        { id: 'creator', name: 'Creator', posts: '25 postów', credits: '500 kredytów', brand: '1 marka', features: ['Brief Intelligence Engine', 'Creative Factory (Mass)', 'Legal & Rights Vault'] },
        { id: 'pro', name: 'Pro', posts: '100 postów', credits: '2 500 kredytów', brand: 'Multi-brand', popular: true, features: ['Wszystko w Creator', 'Media Automator', 'ROI Reports', 'Feedback Loop Engine'] },
        { id: 'enterprise', name: 'Enterprise', posts: '500 postów', credits: '10 000 kredytów', brand: 'Unlimited', features: ['Wszystko w Pro', 'Integracje CRM/VFX', 'Audyt prawny', 'SSO/SLA', 'Brand Policy Engine'] },
        { id: 'studioplus', name: 'Studio+', posts: 'Unlimited postów', credits: '20 000 kredytów', brand: 'Unlimited', features: ['Wszystko w Enterprise', 'Onboarding VIP', 'Priorytetowy support', 'Dedykowany ekspert AIOPOST'] }
      ],
      billed_yearly: "Płatne rocznie",
      billed_monthly: "Płatne miesięcznie",
      per_month: "/mies.",
      cta: "Wybierz plan",
      footnotes: {
          overage: "Koszty dodatkowe (overage):",
          overage_details: "Obraz $0.04/szt., Wideo $0.18–$0.35/sek., Głos $0.06/100 znaków.",
          prepaid: "Pakiety Pre-paid:",
          prepaid_details: "Kup $1000 w kredytach, otrzymaj 12 000 (bonus 20%).",
          onboarding: "Opłaty wdrożeniowe (onboarding fee):",
          onboarding_details: "Pro $1,500 / Enterprise $6,000 / Studio+ $10,000.",
          estimator_note: "Wideo liczone jest sekundowo. Nasz estymator zawsze pokaże koszt przed renderowaniem.",
      }
    },
    trust: {
        title: "Zaufanie i bezpieczeństwo w standardzie.",
        description: "Budujemy na fundamentach bezpieczeństwa, zgodności i transparentności.",
        badges: [
            "C2PA/SynthID",
            "Zgodność z RODO",
            "Enterprise-grade security",
            "SSO / SLA",
        ],
        box_title: "Czy content generowany przez AI jest bezpieczny prawnie?",
        box_content: "Tak. W AIO AUTOMATE™ każdy wygenerowany asset jest oznaczany cyfrowym \"znakiem wodnym\" C2PA/SynthID, który potwierdza jego pochodzenie. Dodatkowo, wraz z subskrypcją, otrzymujesz pełen transfer praw autorskich do komercyjnego wykorzystania wszystkich wygenerowanych materiałów. Masz pewność i spokój.",
    },
    faq: {
      title: "Często zadawane pytania",
      questions: [
        { question: "Czy mogę używać własnych materiałów?", answer: "Oczywiście. Platforma pozwala na import własnych materiałów (wideo, grafiki, audio), które mogą być analizowane, edytowane i wykorzystywane w generowanych kampaniach. Nasze AI respektuje Brand Kit, zapewniając spójność z Twoimi zasobami." },
        { question: "Jak działają kredyty i estymator kosztu renderu?", answer: "Kredyty to uniwersalna waluta platformy. Każda operacja generowania (obraz, wideo, tekst, audio) zużywa określoną liczbę kredytów. Przed każdym renderem nasz estymator precyzyjnie określi koszt, dając Ci pełną kontrolę nad wydatkami." },
        { question: "Czy platforma publikuje automatycznie?", answer: "Tak. AIO AUTOMATE™ integruje się z popularnymi platformami społecznościowymi (Meta, TikTok i inne), umożliwiając automatyczne planowanie i publikację zatwierdzonych treści zgodnie z ustalonym harmonogramem." },
        { question: "Czy wspieracie badania focusowe?", answer: "Pracujemy nad modułem Focus Intelligence, który pozwoli na przeprowadzanie badań focusowych wygenerowanych kreacji na wczesnym etapie. Funkcjonalność ta jest planowana na Q4. Zapisz się do newslettera, by otrzymać informację o jej starcie." },
        { question: "Na jakich modelach działa AI Core?", answer: "Nasz AI Core to dynamiczny system, który korzysta z wielu wyspecjalizowanych modeli AI (obraz, wideo, audio, językowe). Dobieramy najlepsze narzędzie do danego zadania w czasie rzeczywistym, aby zapewnić najwyższą jakość i efektywność, bez przywiązywania się do jednego dostawcy." }
      ]
    },
    waitlistForm: {
      title: "Dołącz do listy zainteresowanych",
      description: "Bądź pierwszy w kolejce. Zostaw swoje dane, a poinformujemy Cię o starcie platformy i specjalnych ofertach dla pionierów.",
      form: {
        firstName: "Imię",
        lastName: "Nazwisko",
        industry: "Rodzaj firmy / Branża",
        email: "Adres email",
        submit: "Wyślij zgłoszenie",
        submitting: "Wysyłanie...",
        success: "Dziękujemy! Twoje zgłoszenie zostało pomyślnie wysłane. Skontaktujemy się z Tobą wkrótce.",
        error: "Wystąpił błąd. Spróbuj ponownie później.",
      }
    },
    footer: {
      links: {
        policy: "Polityka praw autorskich AI",
        gdpr: "RODO",
        c2pa: "C2PA",
        contact: "Kontakt",
      },
      copyright: "Wszelkie prawa zastrzeżone.",
    },
    creatorPlan: {
      back_button: "Wróć do wszystkich planów",
      title: "Plan Creator",
      description: "Twoje osobiste studio marketingowe. Idealne na start, by tworzyć spójny i profesjonalny content.",
      price_label: "Cena miesięczna",
      credits_label: "Kredyty",
      posts_brands_label: "Posty / Marki",
      price: "$299",
      credits: "500",
      posts_brands: "25 / 1",
      features_title: "Co zawiera plan Creator?",
      features: [
        { name: "Brief Intelligence Engine", description: "Analizuje proste briefy tekstowe i URL-e, aby zrozumieć cele Twojej kampanii i zaproponować trafne koncepcje kreatywne." },
        { name: "Creative Factory (Mass)", description: "Generuje dziesiątki wariantów obrazów i tekstów reklamowych. Idealne do testów A/B nagłówków, wizualizacji i haseł na social media." },
        { name: "Legal & Rights Vault", description: "Każdy wygenerowany asset otrzymuje certyfikat C2PA/SynthID i pełen transfer praw do użytku komercyjnego. Tworzysz z pełnym spokojem ducha." },
      ],
      who_is_it_for_title: "Dla kogo jest ten plan?",
      who_is_it_for_description: "Plan Creator został zaprojektowany z myślą o osobach i małych zespołach, które potrzebują regularnego i wysokiej jakości contentu, ale nie dysponują dużym budżetem ani rozbudowanym działem marketingu.",
      audience: ["Freelancerzy i Solopreneurzy", "Małe firmy i startupy", "Twórcy internetowi i influencerzy"],
      cta: "Zacznij z planem Creator",
    },
    proPlan: {
      back_button: "Wróć do wszystkich planów",
      title: "Plan Pro",
      popular: "Najpopularniejszy",
      description: "Silnik wzrostu dla agencji i marek D2C. Pełna automatyzacja i analityka do skalowania działań.",
      price_label: "Cena miesięczna",
      credits_label: "Kredyty",
      posts_brands_label: "Posty / Marki",
      price: "$890",
      credits: "2 500",
      posts_brands: "100 / Multi",
      features_title: "Co zawiera plan Pro?",
      features_prefix: "Wszystko w Creator, oraz:",
      features: [
        { name: "Media Automator", description: "Połącz konta Meta, TikTok, LinkedIn i planuj publikacje na tygodnie do przodu. Nasz system sam dobierze najlepsze pory." },
        { name: "ROI Reports", description: "Śledź kluczowe metryki (zaangażowanie, konwersje) bezpośrednio w panelu. Zobacz, które kreacje przynoszą najlepsze rezultaty." },
        { name: "Feedback Loop Engine", description: "Oznaczaj ulubione kreacje. AI uczy się Twojego stylu i z każdą kampanią dostarcza bardziej trafne propozycje." },
      ],
      who_is_it_for_title: "Dla kogo jest ten plan?",
      who_is_it_for_description: "Idealne rozwiązanie dla dynamicznych zespołów, które zarządzają wieloma markami lub kampaniami i potrzebują zaawansowanych narzędzi do optymalizacji i raportowania wyników.",
      audience: ["Agencje marketingowe i kreatywne", "Marki D2C i eCommerce", "Zespoły marketingowe w średnich firmach"],
      cta: "Wybierz najpopularniejszy plan",
    },
    enterprisePlan: {
      back_button: "Wróć do wszystkich planów",
      title: "Plan Enterprise",
      description: "Skalowalna automatyzacja dla dużych organizacji z pełną kontrolą, bezpieczeństwem i integracjami.",
      price_label: "Cena miesięczna",
      credits_label: "Kredyty",
      posts_brands_label: "Posty / Marki",
      price: "$3500",
      credits: "10 000",
      posts_brands: "500 / Unlimited",
      features_title: "Co zawiera plan Enterprise?",
      features_prefix: "Wszystko w Pro, oraz:",
      features: [
        { name: "Integracje CRM/VFX", description: "Połącz AIO AUTOMATE™ z HubSpot, Salesforce, Adobe After Effects czy Nuke. Zautomatyzuj przepływ danych i assetów." },
        { name: "Audyt prawny i zgodność", description: "Nasi eksperci pomogą w audycie zgodności generowanych treści z wewnętrznymi regulacjami Twojej firmy." },
        { name: "SSO/SLA", description: "Logowanie jednokrotne (Single Sign-On) dla bezpieczeństwa i umowa o poziomie usług (SLA) gwarantująca niezawodność." },
        { name: "Brand Policy Engine", description: "Zdefiniuj twarde reguły (guardrails), np. \"nie pokazuj logo konkurencji\". AI będzie ich bezwzględnie przestrzegać." },
      ],
      who_is_it_for_title: "Dla kogo jest ten plan?",
      who_is_it_for_description: "Stworzony dla dużych firm i korporacji, które wymagają najwyższych standardów bezpieczeństwa, pełnej integracji z istniejącymi systemami i zaawansowanej kontroli nad procesem twórczym.",
      audience: ["Duże korporacje i holdingi", "Firmy z branż regulowanych", "Międzynarodowe marki"],
      cta: "Skontaktuj się w sprawie Enterprise",
    },
    studioPlusPlan: {
      back_button: "Wróć do wszystkich planów",
      title: "Plan Studio+",
      description: "Partnerstwo strategiczne. Usługi white-glove i dedykowane wsparcie ekspertów dla najbardziej wymagających.",
      price_label: "Cena miesięczna",
      credits_label: "Kredyty",
      posts_brands_label: "Posty / Marki",
      price: "$6500",
      credits: "20 000",
      posts_brands: "Unlimited",
      features_title: "Co zawiera plan Studio+?",
      features_prefix: "Wszystko w Enterprise, oraz:",
      features: [
        { name: "Onboarding VIP", description: "Spersonalizowany, wieloetapowy proces wdrożenia dla całego Twojego zespołu, prowadzony przez naszych najlepszych specjalistów." },
        { name: "Priorytetowy support 24/7", description: "Dostęp do dedykowanej linii wsparcia z gwarantowanym czasem odpowiedzi poniżej 15 minut." },
        { name: "Dedykowany ekspert AIOPOST", description: "Twój osobisty strateg, który pomoże Ci maksymalnie wykorzystać potencjał platformy, optymalizować briefy i analizować wyniki." },
      ],
      who_is_it_for_title: "Dla kogo jest ten plan?",
      who_is_it_for_description: "Kompleksowe rozwiązanie dla globalnych marek i wiodących agencji, które traktują automatyzację jako strategiczny element przewagi konkurencyjnej i oczekują najwyższego poziomu obsługi.",
      audience: ["Globalne marki i domy mediowe", "Wiodące agencje reklamowe", "Organizacje realizujące kampanie o dużej skali"],
      cta: "Porozmawiaj o partnerstwie Studio+",
    },
    demoPage: {
      back_button: "Wróć do strony głównej",
      title: "Zobacz Demo AIO AUTOMATE™ (2 min)",
      description: "Zobacz, jak nasza platforma przekształca brief w gotową do publikacji kampanię w zaledwie kilka minut.",
      video_alt: "Video placeholder",
      points: [
        { title: "Od Briefu do Wyników", description: "Analiza, kreacja, postprodukcja i publikacja – wszystko w jednym, płynnym procesie." },
        { title: "Pełna Kontrola", description: "Zobacz panel Fine-Control w akcji i dowiedz się, jak precyzyjnie dostosować każdy element kampanii." },
        { title: "Bezpieczeństwo Prawne", description: "Zrozum, jak C2PA/SynthID i transfer praw chronią Twoją markę na każdym kroku." },
      ],
      cta_title: "Gotów na kolejny krok?",
      cta_description: "Nasze demo to dopiero początek. Umów się na spersonalizowaną prezentację, aby zobaczyć, jak AIO AUTOMATE™ może rozwiązać Twoje konkretne wyzwania.",
      cta_button: "Umów indywidualne demo",
    },
    policyPage: {
      back_button: "Wróć do strony głównej",
      title: "Polityka Praw Autorskich AI",
      last_updated: "Ostatnia aktualizacja: 24 lipca 2024",
      placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      sections: [
        "Własność Treści Generowanych",
        "Transfer Praw do Użytku Komercyjnego",
        "Standardy C2PA/SynthID",
        "Odpowiedzialność Użytkownika",
      ],
    },
    gdprPage: {
      back_button: "Wróć do strony głównej",
      title: "Zgodność z RODO (GDPR)",
      description: "W AIO AUTOMATE™ priorytetowo traktujemy prywatność i bezpieczeństwo danych.",
      placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Curabitur quis lectus et justo auctor fringilla. In hac habitasse platea dictumst. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
      sections: [
        "Administrator Danych",
        "Prawa Użytkownika",
        "Bezpieczeństwo Danych",
        "Przetwarzanie Danych przez AI",
      ],
    },
    c2paPage: {
      back_button: "Wróć do strony głównej",
      title: "Standard C2PA i SynthID",
      description: "Budujemy przyszłość transparentnych i autentycznych mediów cyfrowych.",
      section1_title: "Czym jest C2PA?",
      section1_content: "C2PA (Coalition for Content Provenance and Authenticity) to otwarty standard techniczny, który pozwala twórcom i konsumentom prześledzić pochodzenie i historię mediów cyfrowych. Działa jak cyfrowa \"etykieta żywieniowa\" dla treści, dostarczając wiarygodnych informacji o tym, kto, jak i kiedy stworzył dany obraz czy wideo.",
      section2_title: "Jak to działa w AIO AUTOMATE™?",
      section2_content: "Każdy pojedynczy asset (obraz, wideo, audio) wygenerowany na naszej platformie jest automatycznie oznaczany metadanymi C2PA oraz niewidocznym znakiem wodnym SynthID. Ten cyfrowy podpis jest trwale powiązany z plikiem i zawiera informacje o:",
      section2_points: [
        "Użyciu AI w procesie tworzenia.",
        "Dacie i czasie generacji.",
        "Tożsamości posiadacza konta (w sposób zanonimizowany).",
      ],
      section3_title: "Korzyści dla Twojej Marki",
      section3_points: [
        { name: "Zaufanie i Wiarygodność:", text: "Pokaż swoim odbiorcom, że jesteś transparentny w kwestii użycia AI." },
        { name: "Ochrona Prawna:", text: "Masz niepodważalny dowód pochodzenia i własności treści." },
        { name: "Walka z Dezinformacją:", text: "Dołącz do globalnego ruchu na rzecz odpowiedzialnych i autentycznych mediów." },
      ],
    },
    contactPage: {
      back_button: "Wróć do strony głównej",
      title: "Skontaktuj się z nami",
      description: "Masz pytania? Chcesz porozmawiać o planie Enterprise? Jesteśmy do Twojej dyspozycji.",
      form_title: "Wyślij wiadomość",
      form: {
        fullName: "Imię i nazwisko",
        email: "Adres email",
        message: "Twoja wiadomość",
        submit: "Wyślij",
        success: "Dziękujemy za wiadomość! Odpowiemy najszybciej, jak to możliwe.",
      },
      sales_title: "Sprzedaż i plany Enterprise",
      sales_email: "sprzedaz@aio-automate.example.com",
      support_title: "Wsparcie techniczne",
      support_email: "pomoc@aio-automate.example.com",
      address_title: "Adres biura",
      address_lines: ["AIO AUTOMATE™ Inc.", "ul. Innowacji 42", "00-123 Warszawa, Polska"],
    },
    loginPage: {
        title: "Witaj z powrotem",
        description: "Zaloguj się, aby kontynuować do AIO AUTOMATE™.",
        form: {
            email: "Adres email",
            password: "Hasło",
            submit: "Zaloguj się",
        },
        register_prompt: "Nie masz konta?",
        register_link: "Zarejestruj się",
        sso_google: "Kontynuuj z Google",
    },
    registerPage: {
        title: "Stwórz konto",
        description: "Zacznij automatyzować swój marketing w kilka minut.",
        form: {
            fullName: "Imię i nazwisko",
            company: "Nazwa firmy",
            email: "Adres email",
            password: "Hasło",
            submit: "Stwórz konto",
        },
        login_prompt: "Masz już konto?",
        login_link: "Zaloguj się",
        sso_google: "Zarejestruj się z Google",
    },
    dashboard: {
        sidebar: {
            dashboard: "Panel główny",
            campaigns: "Kampanie",
            brand: "Ustawienia marki",
            billing: "Płatności",
            analytics: "Analityka",
        },
        welcome: {
            title: "Witaj w AIO AUTOMATE™, {{name}}!",
            description: "Jesteś gotów, by rozpocząć. Oto kilka kroków, które pomogą Ci stworzyć pierwszą kampanię.",
            getStarted: "Zaczynajmy",
        },
        gettingStarted: {
            title: "Pierwsze kroki",
            steps: [
                { name: 'Skonfiguruj markę', description: 'Dodaj swoje logo, kolory i głos marki, aby AI tworzyło spójne kreacje.', cta: 'Ustawienia marki' },
                { name: 'Stwórz pierwszą kampanię', description: 'Zdefiniuj cel, prześlij brief i pozwól AI wygenerować pierwsze koncepcje.', cta: 'Nowa kampania' },
                { name: 'Przejrzyj assety', description: 'Zobacz wygenerowane kreacje, przekaż feedback lub zatwierdź je do publikacji.', cta: 'Zobacz kampanie' },
                { name: 'Zaplanuj publikację', description: 'Połącz swoje kanały social media i zaplanuj publikację jednym kliknięciem.', cta: 'Ustawienia' },
            ]
        },
        campaignsPage: {
            title: "Kampanie",
            new_campaign: "Nowa kampania",
            table_headers: {
                name: "Nazwa kampanii",
                status: "Status",
                channels: "Kanały",
                timeline: "Okres",
                actions: "Akcje",
            },
            view_button: "Zobacz"
        },
        brandSettingsPage: {
            title: "Ustawienia marki / Brand Book",
            description: "Wprowadź kluczowe elementy swojej marki, aby AI mogło tworzyć w 100% spójne i autentyczne kampanie.",
            save_button: "Zapisz zmiany",
            form_sections: {
                basic: "Podstawowe informacje",
                visuals: "Identyfikacja wizualna",
                ideology: "Ideologia Marki",
                legal: "Ustawienia prawne i AI",
            },
            fields: {
                name: { label: "Nazwa Marki", placeholder: "np. AIO AUTOMATE™" },
                industry: { label: "Branża", placeholder: "np. Technologia, Marketing, SaaS" },
                tagline: { label: "Slogan / Tagline", placeholder: "np. From brief to broadcast." },
                logo_light: { label: "Logo (jasne tło)" },
                logo_dark: { label: "Logo (ciemne tło)" },
                primary_color: { label: "Kolor główny" },
                secondary_color: { label: "Kolor dodatkowy" },
                accents: { label: "Akcenty kolorystyczne", placeholder: "#hex1, #hex2" },
                heading_font: { label: "Font nagłówków", placeholder: "np. Sora" },
                body_font: { label: "Font tekstu głównego", placeholder: "np. Inter" },
                mission: { label: "Misja Marki", placeholder: "Jaka jest misja Państwa firmy? Co staracie się osiągnąć?" },
                vision: { label: "Wizja Marki", placeholder: "Jaka jest długoterminowa wizja? Gdzie widzicie swoją markę za 5-10 lat?" },
                values: { label: "Kluczowe Wartości (jedna na linię)", placeholder: "Innowacja\nZaufanie\nJakość" },
                personality: { label: "Osobowość / Archetyp Marki", placeholder: "np. Mędrzec, Odkrywca, Bohater..." },
                target_audience: { label: "Charakterystyka Grupy Docelowej", placeholder: "Opisz idealnego klienta, jego potrzeby, wartości i zachowania." },
                ai_allowed: { label: "Przetwarzanie przez AI", description: "Zezwól AI na analizę i wykorzystanie publicznie dostępnych informacji o marce." },
                c2pa: { label: "Standard C2PA/SynthID", enforced: "Wymuszony", optional: "Opcjonalny" },
            }
        }
    },
    campaignCreator: {
        title: "Kreator Kampanii",
        exit: "Wyjdź z kreatora",
        progress: ["Brief", "Koncepcja", "Treść", "Podsumowanie"],
        brief: {
            title: "1. Stwórz brief kampanii",
            description: "Wypełnij poniższe pola, aby nasze AI mogło zrozumieć Twoje cele i wygenerować trafne propozycje.",
            brand_section: "Marka",
            brand_select: "Wybierz markę",
            basic_section: "Podstawowe informacje",
            name_label: "Nazwa kampanii",
            name_placeholder: "np. Letnia Wyprzedaż 2025",
            goal_label: "Cel kampanii",
            goals: ["Zwiększenie świadomości", "Sprzedaż", "Wprowadzenie produktu", "Rekrutacja"],
            product_label: "Opis produktu / usługi",
            product_placeholder: "Opisz krótko, co promujesz.",
            target_label: "Grupa docelowa",
            target_placeholder: "np. Kobiety 20-35, zainteresowane modą, mieszkające w dużych miastach",
            message_label: "Kluczowy przekaz / oferta",
            message_placeholder: "np. -20% na całą nową kolekcję",
            cta_label: "Call to Action (CTA)",
            cta_placeholder: "np. Kup teraz, Dowiedz się więcej",
            channels_label: "Kanały",
            file_label: "Załącz brief (opcjonalnie)",
            file_description: "Prześlij plik PDF/DOCX z dodatkowymi szczegółami.",
            generate_button: "Generuj Koncepcję",
            generating_button: "AI myśli...",
        },
        concepts: {
            title: "2. Wybierz koncepcję kreatywną",
            description: "Nasze AI przygotowało kilka propozycji na podstawie Twojego briefu. Wybierz tę, która najbardziej Ci odpowiada.",
            select_button: "Wybierz i kontynuuj",
            generating_error: "Wystąpił błąd podczas generowania koncepcji. Spróbuj ponownie.",
        },
        content: {
            title: "3. Podgląd i edycja treści",
            description: "Oto wstępna propozycja treści dla Twojej kampanii. Możesz ją teraz zaakceptować lub zasugerować poprawki.",
            post_text_label: "Tekst posta",
            image_label: "Mock-up grafiki",
            feedback_label: "Zasugeruj poprawki (opcjonalnie)",
            feedback_placeholder: "np. Zmień styl na bardziej formalny, dodaj emoji...",
            approve_button: "Zatwierdź treść",
            revise_button: "Generuj nową wersję",
            revising_button: "Poprawiam...",
        },
        overview: {
            title: "4. Podsumowanie i zapis",
            description: "Świetna robota! Twoja kampania jest gotowa. Sprawdź poniższe szczegóły i zapisz projekt.",
            success_message: "Kampania została pomyślnie zapisana jako szkic!",
            section_brief: "Podsumowanie Briefu",
            section_concept: "Wybrana Koncepcja",
            section_content: "Wygenerowana Treść",
            field_name: "Nazwa Kampanii",
            field_goal: "Cel",
            field_target: "Grupa Docelowa",
            field_message: "Kluczowy Przekaz",
            field_cta: "CTA",
            field_channels: "Kanały",
            concept_title: "Tytuł Koncepcji",
            concept_style: "Styl Wizualny",
            save_button: "Zapisz jako szkic",
            saving_button: "Zapisywanie...",
            back_to_campaigns: "Wróć do listy kampanii",
        }
    }
  },
  en: {
    meta: {
      title: "AIO AUTOMATE™ – Marketing Automation from Brief to Broadcast (EN)",
      description: "AI platform for creating and publishing campaigns with a legal-tech layer: C2PA/SynthID, rights transfer, GDPR compliance. From brief to results.",
    },
    header: {
      nav: {
        features: "Features",
        pricing: "Pricing",
        faq: "FAQ",
      },
      cta: "Start Pilot Program",
      login: "Log in",
      register: "Sign up",
      logout: "Log out",
    },
    hero: {
      title: "Marketing Automation",
      subtitle: "from brief to broadcast.",
      description: "Our autonomous AI agents handle the entire campaign process, and a built-in legal-tech layer ensures full legal safety and transparency.",
      badge: "C2PA/SynthID Included",
      cta: "Join the Waitlist"
    },
    problem: {
      pretitle: "The Problem",
      title: "Marketing in the AI era is both a promise and chaos.",
      description: "Marketing teams are drowning in dozens of tools, while pressure on speed, cost, and quality is mounting. Generative AI promises a revolution but introduces legal chaos and the risk of losing brand control.",
      cards: [
        { title: "Scattered Stack", description: "Juggling subscriptions, lack of integration, and data consistency. Time is spent on manual work, not strategy." },
        { title: "Pressure & Compromises", description: "The endless battle between speed, quality, and budget. Creativity gives way to firefighting." },
        { title: "AI Legal Chaos", description: "Who owns the content? Can it be used commercially? Lack of transparency and standards is a real business risk." },
      ]
    },
    solution: {
      pretitle: "The Solution",
      title: "One Platform. Full Control. Total Safety.",
      description: "AIO AUTOMATE™ is an integrated operating system for marketing. We automate the entire campaign lifecycle – from content generation and precise post-production to publishing, analysis, and optimization.",
      points: [
        { title: "End-to-End Workflow:", description: "Generate photos, videos, 3D, and copy in one place." },
        { title: "Fine Control & Post/VFX:", description: "Full control over voice, music, shots, and color grading." },
        { title: "Built-in Legal Layer:", description: "C2PA/SynthID standard, rights transfer, and regulatory compliance." },
      ]
    },
     howItWorks: {
        title: "How It Works. Six Simple Steps.",
        description: "From an idea to a global campaign in the time it used to take to write a single email.",
        steps: [
            { name: '1. Brand Book', description: 'Input your logo, colors, fonts, and tone of voice. Our AI learns your brand to ensure 100% consistency.' },
            { name: '2. Precise Brief', description: 'Define the goal, offer, target, and CTA. Upload PDF files with additional information. Our Brief Intelligence Engine will understand the context.' },
            { name: '3. Campaign Proposals', description: 'Within minutes, you’ll receive 2-3 creative concept variants, fully compliant with your brief and Brand Kit.' },
            { name: '4. Generation & Fine Control', description: 'After concept approval, the platform generates all necessary assets. Use the Fine Control panel for final adjustments.' },
            { name: '5. Publishing', description: 'Integrate your Meta, TikTok, and other accounts. Schedule posts, and our Media Automator will handle the rest.' },
            { name: '6. Analysis & Optimization', description: 'Track results in real-time. The AI Performance Engine analyzes data and suggests automatic adjustments for future campaigns.' },
        ]
    },
    features: {
      title: "Built for Efficiency and Control.",
      description: "Every feature in AIO AUTOMATE™ is designed to eliminate manual work, boost creativity, and ensure complete safety.",
      featureList: [
        { name: 'Brief Intelligence Engine', description: 'Analyzes briefs, documents, and URLs to fully understand campaign context.' },
        { name: 'Brand Kit Lock + Policy Engine', description: 'Guarantees 100% compliance with visual identity and brand policies (guardrails).' },
        { name: 'Creative Factory', description: 'Generates thousands of creative variations (Mass) or single, polished assets (High-End).' },
        { name: 'Feedback Loop Engine', description: 'Learns your taste and preferences from ratings and edits to deliver better proposals over time.' },
        { name: 'Media Automator', description: 'Schedules and publishes content on social media platforms, saving you time.' },
        { name: 'AI Performance Engine', description: 'Analyzes campaign results and provides optimization recommendations.' },
        { name: 'Legal & Rights Vault', description: 'Stores C2PA/SynthID certificates and copyright transfer documents for every asset.' },
        { name: 'Fine Control Panel', description: 'Intuitive post-production tools for precise control over every creative detail.' },
      ]
    },
    integrations: {
        title: "Integrated with the tools you already use",
        description: "AIO AUTOMATE™ connects with your existing tech stack, creating a seamless workflow without context switching. Less clicking, more creating.",
        logos: ['Meta', 'TikTok', 'Google', 'Salesforce', 'Adobe', 'HubSpot', 'Slack', 'Zapier']
    },
    legalSafety: {
      pretitle: "Legal & Safety First",
      title: "Create without fear. Publish with confidence.",
      description: "In an era of misinformation and legal chaos, AIO AUTOMATE™ prioritizes transparency. We are the first platform to integrate C2PA and SynthID standards at every stage, giving you irrefutable proof of content origin and ownership.",
      points: [
        "C2PA/SynthID certificates for every asset",
        "Automatic transfer of rights for commercial use",
        "Compliance with GDPR and the EU AI Act",
        "Transparency of AI models used for generation",
      ],
      highlight: "Every asset gets a C2PA/SynthID. You have clear commercial rights.",
    },
    icp: {
      title: "Built for Leaders. Scalable for Everyone.",
      description: "Regardless of your team's size, AIO AUTOMATE™ adapts to your needs, becoming a powerful tool in the hands of strategists.",
      profiles: [
        { name: 'Marketing Agencies', description: 'From pitch to publication, faster and more independently. Wow clients with speed and quality while reducing operational costs. Scale your services without growing your team.', cta: 'Join the list' },
        { name: 'D2C / eCommerce Brands', description: 'Create unlimited variations of performance content. A built-in optimization loop and ROI analysis will help you maximize conversions and outperform the competition.', cta: 'Join the list' },
        { name: 'Small Businesses & Creators', description: 'Your personal marketing hub. Manage all your marketing yourself, without needing an agency or freelancers. From strategy to daily posts.', cta: 'Join the list' },
      ]
    },
    pricing: {
      title: "Simple Pricing. Powerful Capabilities.",
      description: "Choose a plan that grows with you. Start today and scale without limits.",
      monthly: "Monthly",
      yearly: "Yearly",
      yearly_save: "(-15%)",
      popular: "Most Popular",
      plans: [
        { id: 'creator', name: 'Creator', posts: '25 posts', credits: '500 credits', brand: '1 brand', features: ['Brief Intelligence Engine', 'Creative Factory (Mass)', 'Legal & Rights Vault'] },
        { id: 'pro', name: 'Pro', posts: '100 posts', credits: '2,500 credits', brand: 'Multi-brand', popular: true, features: ['Everything in Creator', 'Media Automator', 'ROI Reports', 'Feedback Loop Engine'] },
        { id: 'enterprise', name: 'Enterprise', posts: '500 posts', credits: '10,000 credits', brand: 'Unlimited', features: ['Everything in Pro', 'CRM/VFX Integrations', 'Legal Audit', 'SSO/SLA', 'Brand Policy Engine'] },
        { id: 'studioplus', name: 'Studio+', posts: 'Unlimited posts', credits: '20,000 credits', brand: 'Unlimited', features: ['Everything in Enterprise', 'VIP Onboarding', 'Priority Support', 'Dedicated AIOPOST Expert'] }
      ],
      billed_yearly: "Billed annually",
      billed_monthly: "Billed monthly",
      per_month: "/mo",
      cta: "Choose Plan",
      footnotes: {
          overage: "Overage costs:",
          overage_details: "Image $0.04/ea, Video $0.18–$0.35/sec, Voice $0.06/100 chars.",
          prepaid: "Pre-paid Packages:",
          prepaid_details: "Buy $1000 in credits, get 12,000 (20% bonus).",
          onboarding: "Onboarding fees:",
          onboarding_details: "Pro $1,500 / Enterprise $6,000 / Studio+ $10,000.",
          estimator_note: "Video is calculated per second. Our estimator will always show the cost before rendering.",
      }
    },
    trust: {
        title: "Trust and Security by Default.",
        description: "We build on a foundation of security, compliance, and transparency.",
        badges: [
            "C2PA/SynthID",
            "GDPR Compliant",
            "Enterprise-grade security",
            "SSO / SLA",
        ],
        box_title: "Is AI-generated content legally safe?",
        box_content: "Yes. At AIO AUTOMATE™, every generated asset is marked with a C2PA/SynthID digital \"watermark\" confirming its origin. Additionally, your subscription includes a full transfer of copyrights for the commercial use of all generated materials. You have certainty and peace of mind.",
    },
    faq: {
      title: "Frequently Asked Questions",
      questions: [
        { question: "Can I use my own assets?", answer: "Of course. The platform allows you to import your own materials (video, graphics, audio), which can be analyzed, edited, and used in generated campaigns. Our AI respects your Brand Kit, ensuring consistency with your resources." },
        { question: "How do credits and the render cost estimator work?", answer: "Credits are the universal currency of the platform. Every generation operation (image, video, text, audio) consumes a certain number of credits. Before each render, our estimator will precisely determine the cost, giving you full control over your expenses." },
        { question: "Does the platform publish automatically?", answer: "Yes. AIO AUTOMATE™ integrates with popular social media platforms (Meta, TikTok, etc.), allowing for automatic scheduling and publication of approved content according to your schedule." },
        { question: "Do you support focus group testing?", answer: "We are working on a Focus Intelligence module that will allow for focus group testing of generated creatives at an early stage. This feature is planned for Q4. Subscribe to our newsletter to be notified of its launch." },
        { question: "What models does the AI Core run on?", answer: "Our AI Core is a dynamic system that uses multiple specialized AI models (image, video, audio, language). We select the best tool for the job in real-time to ensure the highest quality and efficiency, without being tied to a single provider." }
      ]
    },
    waitlistForm: {
      title: "Join the Waitlist",
      description: "Be the first in line. Leave your details, and we'll notify you about the platform launch and special offers for pioneers.",
      form: {
        firstName: "First Name",
        lastName: "Last Name",
        industry: "Company Type / Industry",
        email: "Email Address",
        submit: "Send Application",
        submitting: "Sending...",
        success: "Thank you! Your application has been sent successfully. We will contact you shortly.",
        error: "An error occurred. Please try again later.",
      }
    },
    footer: {
      links: {
        policy: "AI Copyright Policy",
        gdpr: "GDPR",
        c2pa: "C2PA",
        contact: "Contact",
      },
      copyright: "All rights reserved.",
    },
     creatorPlan: {
      back_button: "Back to all plans",
      title: "Creator Plan",
      description: "Your personal marketing studio. Perfect for starting out to create consistent and professional content.",
      price_label: "Monthly Price",
      credits_label: "Credits",
      posts_brands_label: "Posts / Brands",
      price: "$299",
      credits: "500",
      posts_brands: "25 / 1",
      features_title: "What's included in the Creator plan?",
      features: [
        { name: "Brief Intelligence Engine", description: "Analyzes simple text briefs and URLs to understand your campaign goals and propose relevant creative concepts." },
        { name: "Creative Factory (Mass)", description: "Generates dozens of variations of images and ad copy. Ideal for A/B testing headlines, visuals, and slogans on social media." },
        { name: "Legal & Rights Vault", description: "Every generated asset receives a C2PA/SynthID certificate and full rights transfer for commercial use. Create with complete peace of mind." },
      ],
      who_is_it_for_title: "Who is this plan for?",
      who_is_it_for_description: "The Creator plan is designed for individuals and small teams who need regular, high-quality content but do not have a large budget or an extensive marketing department.",
      audience: ["Freelancers and Solopreneurs", "Small businesses and startups", "Content creators and influencers"],
      cta: "Start with Creator Plan",
    },
    proPlan: {
      back_button: "Back to all plans",
      title: "Pro Plan",
      popular: "Most Popular",
      description: "The growth engine for agencies and D2C brands. Full automation and analytics to scale your operations.",
      price_label: "Monthly Price",
      credits_label: "Credits",
      posts_brands_label: "Posts / Brands",
      price: "$890",
      credits: "2,500",
      posts_brands: "100 / Multi",
      features_title: "What's included in the Pro plan?",
      features_prefix: "Everything in Creator, plus:",
      features: [
        { name: "Media Automator", description: "Connect your Meta, TikTok, LinkedIn accounts and schedule posts for weeks ahead. Our system will choose the best times." },
        { name: "ROI Reports", description: "Track key metrics (engagement, conversions) directly in the dashboard. See which creatives deliver the best results." },
        { name: "Feedback Loop Engine", description: "Mark your favorite creatives. The AI learns your style and delivers more accurate proposals with each campaign." },
      ],
      who_is_it_for_title: "Who is this plan for?",
      who_is_it_for_description: "The ideal solution for dynamic teams managing multiple brands or campaigns who need advanced tools for optimization and results reporting.",
      audience: ["Marketing and creative agencies", "D2C and eCommerce brands", "Marketing teams in medium-sized companies"],
      cta: "Choose the Most Popular Plan",
    },
    enterprisePlan: {
      back_button: "Back to all plans",
      title: "Enterprise Plan",
      description: "Scalable automation for large organizations with full control, security, and integrations.",
      price_label: "Monthly Price",
      credits_label: "Credits",
      posts_brands_label: "Posts / Brands",
      price: "$3,500",
      credits: "10,000",
      posts_brands: "500 / Unlimited",
      features_title: "What's included in the Enterprise plan?",
      features_prefix: "Everything in Pro, plus:",
      features: [
        { name: "CRM/VFX Integrations", description: "Connect AIO AUTOMATE™ with HubSpot, Salesforce, Adobe After Effects, or Nuke. Automate data and asset flows." },
        { name: "Legal & Compliance Audit", description: "Our experts will help audit the compliance of generated content with your company's internal regulations." },
        { name: "SSO/SLA", description: "Single Sign-On for security and a Service Level Agreement (SLA) guaranteeing reliability." },
        { name: "Brand Policy Engine", description: "Define hard rules (guardrails), e.g., \"do not show competitor logos.\" The AI will strictly adhere to them." },
      ],
      who_is_it_for_title: "Who is this plan for?",
      who_is_it_for_description: "Designed for large companies and corporations that require the highest security standards, full integration with existing systems, and advanced control over the creative process.",
      audience: ["Large corporations and holdings", "Companies in regulated industries", "International brands"],
      cta: "Contact Us for Enterprise",
    },
    studioPlusPlan: {
      back_button: "Back to all plans",
      title: "Studio+ Plan",
      description: "A strategic partnership. White-glove services and dedicated expert support for the most demanding clients.",
      price_label: "Monthly Price",
      credits_label: "Credits",
      posts_brands_label: "Posts / Brands",
      price: "$6,500",
      credits: "20,000",
      posts_brands: "Unlimited",
      features_title: "What's included in the Studio+ plan?",
      features_prefix: "Everything in Enterprise, plus:",
      features: [
        { name: "VIP Onboarding", description: "A personalized, multi-stage onboarding process for your entire team, led by our top specialists." },
        { name: "24/7 Priority Support", description: "Access to a dedicated support line with a guaranteed response time of under 15 minutes." },
        { name: "Dedicated AIOPOST Expert", description: "Your personal strategist who will help you maximize the platform's potential, optimize briefs, and analyze results." },
      ],
      who_is_it_for_title: "Who is this plan for?",
      who_is_it_for_description: "A comprehensive solution for global brands and leading agencies that view automation as a strategic competitive advantage and expect the highest level of service.",
      audience: ["Global brands and media houses", "Leading advertising agencies", "Organizations running large-scale campaigns"],
      cta: "Discuss a Studio+ Partnership",
    },
    demoPage: {
      back_button: "Back to Homepage",
      title: "Watch the AIO AUTOMATE™ Demo (2 min)",
      description: "See how our platform transforms a brief into a ready-to-publish campaign in just a few minutes.",
      video_alt: "Video placeholder",
      points: [
        { title: "From Brief to Results", description: "Analysis, creation, post-production, and publishing – all in one seamless process." },
        { title: "Full Control", description: "See the Fine-Control panel in action and learn how to precisely adjust every element of your campaign." },
        { title: "Legal Safety", description: "Understand how C2PA/SynthID and rights transfer protect your brand at every step." },
      ],
      cta_title: "Ready for the next step?",
      cta_description: "Our demo is just the beginning. Schedule a personalized presentation to see how AIO AUTOMATE™ can solve your specific challenges.",
      cta_button: "Schedule a Personal Demo",
    },
    policyPage: {
      back_button: "Back to Homepage",
      title: "AI Copyright Policy",
      last_updated: "Last updated: July 24, 2024",
      placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      sections: [
        "Ownership of Generated Content",
        "Transfer of Rights for Commercial Use",
        "C2PA/SynthID Standards",
        "User Responsibility",
      ],
    },
    gdprPage: {
      back_button: "Back to Homepage",
      title: "GDPR Compliance",
      description: "At AIO AUTOMATE™, we prioritize data privacy and security.",
      placeholder: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Curibitur quis lectus et justo auctor fringilla. In hac habitasse platea dictumst. Praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.",
      sections: [
        "Data Controller",
        "User Rights",
        "Data Security",
        "AI Data Processing",
      ],
    },
    c2paPage: {
      back_button: "Back to Homepage",
      title: "C2PA and SynthID Standard",
      description: "Building the future of transparent and authentic digital media.",
      section1_title: "What is C2PA?",
      section1_content: "C2PA (Coalition for Content Provenance and Authenticity) is an open technical standard that allows creators and consumers to trace the origin and history of digital media. It acts like a digital \"nutrition label\" for content, providing credible information about who, how, and when a given image or video was created.",
      section2_title: "How does it work in AIO AUTOMATE™?",
      section2_content: "Every single asset (image, video, audio) generated on our platform is automatically tagged with C2PA metadata and an invisible SynthID watermark. This digital signature is permanently linked to the file and contains information about:",
      section2_points: [
        "The use of AI in the creation process.",
        "The date and time of generation.",
        "The identity of the account holder (in an anonymized way).",
      ],
      section3_title: "Benefits for Your Brand",
      section3_points: [
        { name: "Trust and Credibility:", text: "Show your audience that you are transparent about using AI." },
        { name: "Legal Protection:", text: "You have irrefutable proof of the content's origin and ownership." },
        { name: "Fighting Disinformation:", text: "Join the global movement for responsible and authentic media." },
      ],
    },
    contactPage: {
      back_button: "Back to Homepage",
      title: "Contact Us",
      description: "Have questions? Want to discuss an Enterprise plan? We're here to help.",
      form_title: "Send a message",
      form: {
        fullName: "Full Name",
        email: "Email Address",
        message: "Your Message",
        submit: "Send",
        success: "Thank you for your message! We will respond as soon as possible.",
      },
      sales_title: "Sales & Enterprise Plans",
      sales_email: "sales@aio-automate.example.com",
      support_title: "Technical Support",
      support_email: "support@aio-automate.example.com",
      address_title: "Office Address",
      address_lines: ["AIO AUTOMATE™ Inc.", "42 Innovation Drive", "Warsaw, 00-123, Poland"],
    },
     loginPage: {
        title: "Welcome back",
        description: "Log in to continue to AIO AUTOMATE™.",
        form: {
            email: "Email address",
            password: "Password",
            submit: "Log in",
        },
        register_prompt: "Don't have an account?",
        register_link: "Sign up",
        sso_google: "Continue with Google",
    },
    registerPage: {
        title: "Create an account",
        description: "Start automating your marketing in minutes.",
        form: {
            fullName: "Full name",
            company: "Company name",
            email: "Email address",
            password: "Password",
            submit: "Create account",
        },
        login_prompt: "Already have an account?",
        login_link: "Log in",
        sso_google: "Sign up with Google",
    },
    dashboard: {
        sidebar: {
            dashboard: "Dashboard",
            campaigns: "Campaigns",
            brand: "Brand Settings",
            billing: "Billing",
            analytics: "Analytics",
        },
        welcome: {
            title: "Welcome to AIO AUTOMATE™, {{name}}!",
            description: "You're all set to get started. Here are a few steps to help you create your first campaign.",
            getStarted: "Let's get started",
        },
        gettingStarted: {
            title: "Getting Started",
            steps: [
                { name: 'Configure Your Brand', description: 'Add your logo, colors, and brand voice so the AI can create consistent content.', cta: 'Brand Settings' },
                { name: 'Create Your First Campaign', description: 'Define your goal, upload a brief, and let the AI generate initial concepts.', cta: 'New Campaign' },
                { name: 'Review Assets', description: 'See the generated creatives, provide feedback, or approve them for publishing.', cta: 'View Campaigns' },
                { name: 'Schedule for Publishing', description: 'Connect your social media channels and schedule your posts with one click.', cta: 'Settings' },
            ]
        },
        campaignsPage: {
            title: "Campaigns",
            new_campaign: "New Campaign",
            table_headers: {
                name: "Campaign Name",
                status: "Status",
                channels: "Channels",
                timeline: "Timeline",
                actions: "Actions",
            },
            view_button: "View"
        },
        brandSettingsPage: {
            title: "Brand Settings / Brand Book",
            description: "Enter your brand's key elements so the AI can create 100% consistent and authentic campaigns.",
            save_button: "Save Changes",
            form_sections: {
                basic: "Basic Information",
                visuals: "Visual Identity",
                ideology: "Brand Ideology",
                legal: "Legal & AI Settings",
            },
            fields: {
                name: { label: "Brand Name", placeholder: "e.g., AIO AUTOMATE™" },
                industry: { label: "Industry", placeholder: "e.g., Technology, Marketing, SaaS" },
                tagline: { label: "Tagline", placeholder: "e.g., From brief to broadcast." },
                logo_light: { label: "Logo (for light backgrounds)" },
                logo_dark: { label: "Logo (for dark backgrounds)" },
                primary_color: { label: "Primary Color" },
                secondary_color: { label: "Secondary Color" },
                accents: { label: "Accent Colors", placeholder: "#hex1, #hex2" },
                heading_font: { label: "Heading Font", placeholder: "e.g., Sora" },
                body_font: { label: "Body Font", placeholder: "e.g., Inter" },
                mission: { label: "Brand Mission", placeholder: "What is your company's mission? What are you trying to achieve?" },
                vision: { label: "Brand Vision", placeholder: "What is the long-term vision? Where do you see your brand in 5-10 years?" },
                values: { label: "Key Values (one per line)", placeholder: "Innovation\nTrust\nQuality" },
                personality: { label: "Brand Personality / Archetype", placeholder: "e.g., The Sage, The Explorer, The Hero..." },
                target_audience: { label: "Target Audience Profile", placeholder: "Describe your ideal customer, their needs, values, and behaviors." },
                ai_allowed: { label: "AI Processing", description: "Allow AI to analyze and use publicly available information about the brand." },
                c2pa: { label: "C2PA/SynthID Standard", enforced: "Enforced", optional: "Optional" },
            }
        }
    },
    campaignCreator: {
        title: "Campaign Creator",
        exit: "Exit Creator",
        progress: ["Brief", "Concept", "Content", "Overview"],
        brief: {
            title: "1. Create a Campaign Brief",
            description: "Fill in the fields below so our AI can understand your goals and generate relevant proposals.",
            brand_section: "Brand",
            brand_select: "Select a brand",
            basic_section: "Basic Information",
            name_label: "Campaign Name",
            name_placeholder: "e.g., Summer Sale 2025",
            goal_label: "Campaign Goal",
            goals: ["Awareness", "Sales", "Product Launch", "Recruitment"],
            product_label: "Product / Service Description",
            product_placeholder: "Briefly describe what you're promoting.",
            target_label: "Target Audience",
            target_placeholder: "e.g., Women 20-35, interested in fashion, living in big cities",
            message_label: "Key Message / Offer",
            message_placeholder: "e.g., -20% on the entire new collection",
            cta_label: "Call to Action (CTA)",
            cta_placeholder: "e.g., Buy Now, Learn More",
            channels_label: "Channels",
            file_label: "Attach Brief (optional)",
            file_description: "Upload a PDF/DOCX file with additional details.",
            generate_button: "Generate Concept",
            generating_button: "AI is thinking...",
        },
        concepts: {
            title: "2. Choose a Creative Concept",
            description: "Our AI has prepared a few proposals based on your brief. Choose the one you like best.",
            select_button: "Select & Continue",
            generating_error: "An error occurred while generating concepts. Please try again.",
        },
        content: {
            title: "3. Preview & Edit Content",
            description: "Here's an initial content proposal for your campaign. You can now approve it or suggest edits.",
            post_text_label: "Post Text",
            image_label: "Image Mock-up",
            feedback_label: "Suggest Edits (optional)",
            feedback_placeholder: "e.g., Change the style to be more formal, add emojis...",
            approve_button: "Approve Content",
            revise_button: "Generate New Version",
            revising_button: "Revising...",
        },
        overview: {
            title: "4. Overview & Save",
            description: "Great job! Your campaign is ready. Check the details below and save the project.",
            success_message: "Campaign successfully saved as a draft!",
            section_brief: "Brief Summary",
            section_concept: "Selected Concept",
            section_content: "Generated Content",
            field_name: "Campaign Name",
            field_goal: "Goal",
            field_target: "Target Audience",
            field_message: "Key Message",
            field_cta: "CTA",
            field_channels: "Channels",
            concept_title: "Concept Title",
            concept_style: "Visual Style",
            save_button: "Save as Draft",
            saving_button: "Saving...",
            back_to_campaigns: "Back to Campaigns List",
        }
    }
  }
};
